/**
 * Lawyer Database — NyayaSetu
 * Pre-seeded lawyer profiles. On first run, populates IndexedDB.
 * Embeddings are computed by the EmbeddingService at init time.
 */

export const LAWYER_SEED_DATA = [
  {
    id: 1,
    name: 'Adv. Ananya Sharma',
    rating: 4.8,
    experience: 12,
    isLegalAid: true,
    categories: ['PROPERTY', 'TENANCY', 'CIVIL'],
    location: 'New Delhi',
    distanceKm: 3.2,
    online: true,
    image: 'https://i.pravatar.cc/150?u=a',
    bio: 'Specializes in property disputes, tenancy law, and civil litigation. Expert in Model Tenancy Act and rent control matters.',
    phone: '+91-98100-XXXXX',
    languages: ['Hindi', 'English'],
    consultationFee: 'Free (Legal Aid)',
    // Specialty text used for embedding generation
    specialtyText: 'property dispute tenancy law civil litigation rent control eviction landlord tenant Model Tenancy Act',
  },
  {
    id: 2,
    name: 'Adv. Sameer Desai',
    rating: 4.5,
    experience: 8,
    isLegalAid: false,
    categories: ['CORPORATE', 'REAL ESTATE'],
    location: 'Noida',
    distanceKm: 5.0,
    online: false,
    image: 'https://i.pravatar.cc/150?u=b',
    bio: 'Corporate and real estate law expert with experience in commercial property deals, contracts, and due diligence.',
    phone: '+91-96000-XXXXX',
    languages: ['Hindi', 'English', 'Marathi'],
    consultationFee: '₹2000/hr',
    specialtyText: 'corporate law real estate commercial property contract due diligence business disputes',
  },
  {
    id: 3,
    name: 'Adv. Priya Nair',
    rating: 4.9,
    experience: 15,
    isLegalAid: true,
    categories: ['FAMILY', 'MATRIMONIAL', 'DOMESTIC VIOLENCE'],
    location: 'South Delhi',
    distanceKm: 6.1,
    online: true,
    image: 'https://i.pravatar.cc/150?u=c',
    bio: 'Leading expert in family law, divorce proceedings, child custody, and domestic violence cases. Strong advocate for women\'s rights.',
    phone: '+91-99110-XXXXX',
    languages: ['Hindi', 'English', 'Malayalam'],
    consultationFee: 'Free (Legal Aid)',
    specialtyText: 'family law divorce matrimonial child custody domestic violence women rights alimony maintenance',
  },
  {
    id: 4,
    name: 'Adv. Rajesh Kumar',
    rating: 4.6,
    experience: 10,
    isLegalAid: false,
    categories: ['CRIMINAL', 'FIR', 'BAIL'],
    location: 'East Delhi',
    distanceKm: 7.3,
    online: true,
    image: 'https://i.pravatar.cc/150?u=d',
    bio: 'Criminal defense lawyer with expertise in FIR matters, bail applications, and criminal trials at district and high court levels.',
    phone: '+91-98990-XXXXX',
    languages: ['Hindi', 'English', 'Bhojpuri'],
    consultationFee: '₹1500/hr',
    specialtyText: 'criminal law FIR bail application arrest police custody criminal defense trial high court district court',
  },
  {
    id: 5,
    name: 'Adv. Meena Goswami',
    rating: 4.7,
    experience: 9,
    isLegalAid: true,
    categories: ['LABOUR', 'EMPLOYMENT', 'WRONGFUL TERMINATION'],
    location: 'Gurugram',
    distanceKm: 12.5,
    online: false,
    image: 'https://i.pravatar.cc/150?u=e',
    bio: 'Labour and employment law specialist. Handles wrongful termination, workplace harassment, salary disputes, and PF/ESI matters.',
    phone: '+91-99000-XXXXX',
    languages: ['Hindi', 'English'],
    consultationFee: 'Free (Legal Aid)',
    specialtyText: 'labour law employment wrongful termination workplace harassment salary dispute provident fund ESI gratuity',
  },
  {
    id: 6,
    name: 'Adv. Vikram Singh',
    rating: 4.4,
    experience: 6,
    isLegalAid: false,
    categories: ['CONSUMER', 'CONSUMER PROTECTION', 'E-COMMERCE'],
    location: 'West Delhi',
    distanceKm: 4.8,
    online: true,
    image: 'https://i.pravatar.cc/150?u=f',
    bio: 'Consumer rights advocate with expertise in consumer forum cases, product defects, service deficiency, refund disputes, and e-commerce fraud.',
    phone: '+91-99200-XXXXX',
    languages: ['Hindi', 'English', 'Punjabi'],
    consultationFee: '₹1000/hr',
    specialtyText: 'consumer protection consumer forum product defect service deficiency refund ecommerce fraud consumer rights',
  },
  {
    id: 7,
    name: 'Adv. Sunita Patel',
    rating: 4.8,
    experience: 14,
    isLegalAid: false,
    categories: ['CYBER CRIME', 'IT ACT', 'DATA PRIVACY'],
    location: 'Noida',
    distanceKm: 9.2,
    online: true,
    image: 'https://i.pravatar.cc/150?u=g',
    bio: 'Cyber law specialist handling online fraud, identity theft, hacking, social media harassment, and data privacy violations under the IT Act.',
    phone: '+91-98300-XXXXX',
    languages: ['Hindi', 'English', 'Gujarati'],
    consultationFee: '₹3000/hr',
    specialtyText: 'cyber crime IT act data privacy online fraud identity theft hacking social media harassment cybersecurity digital',
  },
  {
    id: 8,
    name: 'Adv. Arun Mehta',
    rating: 4.5,
    experience: 11,
    isLegalAid: true,
    categories: ['CONSTITUTIONAL', 'FUNDAMENTAL RIGHTS', 'PIL'],
    location: 'Central Delhi',
    distanceKm: 2.1,
    online: false,
    image: 'https://i.pravatar.cc/150?u=h',
    bio: 'Constitutional law expert. Files PILs and fundamental rights petitions. Works on right to education, right to food, and environmental matters.',
    phone: '+91-99500-XXXXX',
    languages: ['Hindi', 'English'],
    consultationFee: 'Free (Legal Aid)',
    specialtyText: 'constitutional law fundamental rights PIL public interest litigation right to education right to food environment article 21',
  },
];
